---
title: "Data First Look"
author: "Sydney Yeargers"
date: "2/23/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Global Emissions
```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggpubr)
ccGlobal <- read.csv('/cloud/project/Data/ClimateChangeGlobal.csv', header=FALSE)
ccGlobal = setNames(data.frame(t(ccGlobal[,-1])), ccGlobal[,1])
ccGlobal = ccGlobal[!is.na(ccGlobal[,1]),0:4]
ccGlobal = ccGlobal %>% rename(year = `Year (C6.1 - 6.5)`,
                               grossScope1 = `Gross global Scope 1 emissions (metric tons CO2e)`,
                               grossScope2Loc = `_Gross global Scope 2, location-based_ (metric tons CO2e)`,
                    grossScope2Mark = `Gross global Scope 2, market-based (metric tons CO2e)`) 

globalScope1 <- ggplot(ccGlobal, aes(x=year, y=grossScope1))+
  geom_point()+geom_line(linetype='dashed')+
  ggtitle("Gross global Scope 1 emissions (metric tons CO2e)")

globalScope2Loc <- ggplot(ccGlobal, aes(x=year, y=grossScope2Loc))+
  geom_point()+geom_line(linetype='dashed')+
  ggtitle("Gross global Scope 2, location-based (metric tons CO2e)")

globalScope2Mark <- ggplot(ccGlobal, aes(x=year, y=grossScope2Mark))+
  geom_point()+geom_line(linetype='dashed')+
  ggtitle("Gross global Scope 2, market-based (metric tons CO2e)")


ggarrange(globalScope1, globalScope2Loc, globalScope2Mark, nrow=2, ncol=2)
```

# By Business Activity
```{r}
ccBusAct <- read.csv('/cloud/project/Data/ClimateChangeBusinessActivity.csv')
ccBusAct = ccBusAct %>% rename(year = Year..C7.3.,
                    scope1 = Scope.1.emissions..metric.tons.CO2e.,
                    scope2Loc = Scope.2..location.based..metric.tons.CO2e.,
                    scope2Mark = Scope.2..market.based..metric.tons.CO2e.) %>%
  select(year,Activity,scope1,scope2Loc,scope2Mark) %>% 
  filter(!is.na(year),
         !is.na(Activity))

BAScope1Plot <- ggplot(ccBusAct, aes(x=year,y=scope1))+
  geom_point()+ facet_wrap(~Activity, scales='free')+
  ggtitle("Scope 1 Emissions")+
  geom_line(linetype='dashed')

BAScope2LocPlot <- ggplot(ccBusAct, aes(x=year,y=scope2Loc))+
  geom_point()+ facet_wrap(~Activity, scales='free')+
  ggtitle("Scope 2 (Location-Based) Emissions")+
  geom_line(linetype='dashed')

BAScope2MarkPlot <- ggplot(ccBusAct, aes(x=year,y=scope2Mark))+
  geom_point()+ facet_wrap(~Activity, scales='free')+
  ggtitle("Scope 2 (Market-Based) Emissions")+
  geom_line(linetype='dashed')

BAScope1Plot
BAScope2LocPlot
BAScope2MarkPlot
```

# By Greenhouse Gas
```{r}
ccGas <- read.csv('/cloud/project/Data/CCGas.csv')
ccGas = ccGas %>% rename(year = Year..C7.1a.,
                         emissions = Scope.1.Emissions..metric.tons.CO2e.)

GasPlot <- ggplot(ccGas, aes(x=year, y=emissions))+
  geom_point()+ facet_wrap(~Gas, scales='free')+
  ggtitle("Emissions by Greenhouse Gas")+
  geom_line(linetype='dashed')
GasPlot
```

# By Area
```{r}
ccArea <- read.csv('/cloud/project/Data/CCArea.csv')
ccArea = ccArea %>% rename(year = Year..C7.2.7.5.,
                         scope1 = Scope.1.Emissions..metric.tons.CO2e.,
                         scope2Loc = Scope.2..location.based..metric.tons.CO2e.,
                         scope2Mark = Scope.2..market.based..metric.tons.CO2e.,
                         ElHeStCool = Purchased.and.consumed.electricity..heat..steam.or.cooling..MWh.,
                         lowCarbElHeStCool = Purchased.and.consumed.low.carbon.electricity..heat..steam.or.cooling.accounted.for.in.Scope.2.market.based.approach..MWh.)%>% 
  filter(!is.na(Area))

ccArea$Area[ccArea$Area=="Latin America (LATAM)"]="Latin America and Caribbean (LAC)"
ccArea = ccArea[!(ccArea$Area=="Canada"|ccArea$Area=="United States of America"),]
AreaScope1Plot <- ggplot(ccArea, aes(x=year, y=scope1))+
  geom_point()+ facet_wrap(~Area, scales='free')+
  ggtitle("Scope 1 Emissions by Location")+
  geom_line(linetype='dashed')
AreaScope1Plot
```
```{r}
AreaScope2LocPlot <- ggplot(ccArea, aes(x=year, y=scope2Loc))+
  geom_point()+ facet_wrap(~Area, scales='free')+
  ggtitle("Scope 2 (location-based) Emissions by Location")+
  geom_line(linetype='dashed')
AreaScope2LocPlot
```
```{r}
AreaScope2MarkPlot <- ggplot(ccArea, aes(x=year, y=scope2Mark))+
  geom_point()+ facet_wrap(~Area, scales='free')+
  ggtitle("Scope 2 (market-based) Emissions by Location")+
  geom_line(linetype='dashed')
AreaScope2MarkPlot
```

```{r}
ggplot(ccArea, aes(x=year))+
  geom_point(aes(y=ElHeStCool), color="blue")+
  geom_line(aes(y=ElHeStCool), color="blue",linetype="dashed")+
  geom_point(aes(y=lowCarbElHeStCool), color="purple")+
  geom_line(aes(y=lowCarbElHeStCool), color="purple",linetype="dashed")+
  facet_wrap(~Area, scales='free')+
  ggtitle("Purchased and Consumed Electricity, Heat, Steam, or Cooling by Location")
```

# By Consumption Type
```{r}
ccConType <- read.csv('/cloud/project/Data/EnergyConsumptionOverview.csv')
ccConType = ccConType %>% rename(year = Year..C8.2.,
                         conType = Consumption.Type..purchased.or.aquired.,
                         MWhRenew = MWh.from.renewable.sources,
                         MWhNonRenew = MWh.from.non.renewable.sources,
                         MWhTotal = Total..renewable.and.non.renewable..MWh) %>%
  select(year,conType,MWhRenew,MWhNonRenew,MWhTotal) %>%
  filter(!is.na(conType))

ggplot(ccConType, aes(x=year))+
  geom_point(aes(y=MWhTotal), color="black")+
  geom_line(aes(y=MWhTotal), color="black",linetype="dashed")+
  geom_point(aes(y=MWhRenew), color="blue")+
  geom_line(aes(y=MWhRenew), color="blue",linetype="dashed")+
  geom_point(aes(y=MWhNonRenew), color="purple")+
  geom_line(aes(y=MWhNonRenew), color="purple",linetype="dashed")+
  facet_wrap(~conType, scales='free')+
  ggtitle("")
```
# By Fuel Breakdown

```{r}
FuelBreakdownType <- read.csv('/cloud/project/Data/FuelUseBreakdown.csv')
FuelBreakdownType = FuelBreakdownType %>% rename(year = Year..C8.2c.,
                         fuelType = Fuel.Type,
                         totalFuel = Total.fuel.MWh.consumed.by.the.organization,
                         MWhElectric = MWh.fuel.consumed.for.self.generation.of.electricity,
                         MWhHeat = MWh.fuel.consumed.for.self.generation.of.heat,
                         EmissFactor = Emission.factor..metric.tons.CO2e.per.MWh.) %>%
  select(year,fuelType,totalFuel,MWhElectric,MWhHeat,EmissFactor) %>%
  filter(!is.na(fuelType))

 

ggplot(FuelBreakdownType, aes(x=year))+
  geom_point(aes(y=totalFuel), color="black")+
  geom_line(aes(y=totalFuel), color="black",linetype="dashed")+
  geom_point(aes(y=MWhElectric), color="blue")+
  geom_line(aes(y=MWhElectric), color="blue",linetype="dashed")+
  geom_point(aes(y=MWhHeat), color="purple")+
  geom_line(aes(y=MWhHeat), color="purple",linetype="dashed")+
  geom_point(aes(y=EmissFactor), color="red")+
  geom_line(aes(y=EmissFactor), color="red",linetype="dashed")+
  facet_wrap(~fuelType, scales='free')+
  ggtitle("Fuel Type Breakdown")
```

# By Water Discharge

```{r}
WaterDischarge <- read.csv('/cloud/project/Data/WaterDischarge.csv')
WaterDischarge = WaterDischarge %>% rename(year = Year..W1.2i.,
                         waterType = Type,
                         Volume = Volume..megaliters.year.,) %>%
  select(year,waterType,Volume) %>%
  filter(!is.na(waterType))

 

ggplot(WaterDischarge, aes(x=year))+
  geom_point(aes(y=Volume), color="blue")+
  geom_line(aes(y=Volume), color="blue",linetype="dashed")+
  facet_wrap(~waterType, scales='free')+
  ggtitle("Water Discharge by Type")
```

# By Water Withdrawal

```{r}
WaterWithdrawal <- read.csv('/cloud/project/Data/WaterWithdrawal.csv')
WaterWithdrawal = WaterWithdrawal %>% rename(year = Year..W1.2h.,
                         waterType = Water.Source,
                         Volume = Volume..megaliters.year.,) %>%
  select(year,waterType,Volume) %>%
  filter(!is.na(waterType))

 

ggplot(WaterWithdrawal, aes(x=year))+
  geom_point(aes(y=Volume), color="blue")+
  geom_line(aes(y=Volume), color="blue",linetype="dashed")+
  facet_wrap(~waterType, scales='free')+
  ggtitle("Water Withdrawal by Type")
```